### ISSUE TITLE
JS API generation fails due to jsdossier exception, illegal char

### ISSUE THREAD

**Issue by clawfrank** [ngageoint/opensphere#958]
I'm trying to figure out how to adapt OpenSphere for my usage but I can't seem to find an API for the JS. Does such a thing exist?

I tried using JSDoc to generate one but it just gives me an unstructured list of several hundred classes, which is more useful than digging through the files, but still pretty hard to use.

Is there a certain editor I can use? Another JS doc generation library that does better?

**Comment by bradh** [comment]
From the README.md:

```
API documentation can be built locally by running npm run apidoc, which outputs to dist/apidoc.
```

However that probably isn't the best place to start. I recommend https://opensphere.readthedocs.io/en/latest/guides/plugin_guide.html instead. Reading the code (in VS Code) is also good...

If you have something specific you need help with, I've had awesome results asking on the Slack channel - the core team is really response.

HTH.

**Comment by clawfrank** [comment]
Oh, I thought that was to rebuild the handwritten guides for some reason.

I tried it in git bash but it doesn't seem to work...

```
Processing js-dossier configuration file...
Adding 1912 files to js-dossier sources...
Writing JSDoc configuration to: E:\git\opensphere-yarn-workspace\workspace\opensphere\.build\dossier.conf.json
Exception in thread "main"
java.nio.file.InvalidPathException: Illegal char <*> at index 8: externs/*.js
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at sun.nio.fs.AbstractPath.resolve(Unknown Source)
        at com.github.jsdossier.Config$PathSpec.resolve(Config.java:773)
        at com.github.jsdossier.Config$ImmutablePathSetDeserializer.deserialize(Config.java:981)
        at com.github.jsdossier.Config$ConfigMarshaller.deserialize(Config.java:883)
        at com.github.jsdossier.Config$ConfigMarshaller.deserialize(Config.java:814)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:865)
        at com.github.jsdossier.Config.fromJson(Config.java:610)
        at com.github.jsdossier.Config.fromFlags(Config.java:602)
        at com.github.jsdossier.Main.run(Main.java:96)
        at com.github.jsdossier.Main.main(Main.java:217)
```

**Comment by bradh** [comment]
I just tried it in Linux, and while I don't see that problem, I do see a different problem in jsdossier (later than this, I think).

**Comment by bradh** [comment]
@schmidtk I think this can be closed now jsdossier is removed.

**Comment by schmidtk** [comment]
Thanks @bradh. We will look into reviving our API docs after we migrate all of our source to ES modules, but that will take some time.
